### ISSUE TITLE
Simplify condition using functions

### ISSUE THREAD

**Issue by GauthierPLM** [beSyl/Projet3#3]
https://github.com/beSyl/Projet3/blob/f11a6d3ff7347fc13a63aacbc9da8487bf611f9e/game.py#L65-L70

You should use a function to simplify this condition and avoid too long line. This would also make the code more readable.

**Comment by beSyl** [comment]
Function 'my_pygame.show_destiny(mac_gyver)'.
Updated in an earlier commit.
